// 1st Question.....
alert("Rohit Kumar");

// 2nd Question.....
console.log(Date())

// 3rd Question.....
document.body.innerHTML = 'Rohit Kumar';
// This statement will overwrite the whole already exist webpage content with their own content.

// 4th Question.....
document.body.innerHTML = '';
